# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "87f4fc4b-3a84-497c-a933-141630e2adef",
# META       "default_lakehouse_name": "demolakehouse",
# META       "default_lakehouse_workspace_id": "b4cc010a-7b33-4d70-8970-4f8c2b5eec47",
# META       "known_lakehouses": [
# META         {
# META           "id": "87f4fc4b-3a84-497c-a933-141630e2adef"
# META         },
# META         {
# META           "id": "5ce98252-3d8a-403f-b86b-00c32df3c163"
# META         }
# META       ]
# META     }
# META   }
# META }

# CELL ********************

# Welcome to your new notebook
# Type here in the cell editor to add code!


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC SELECT * FROM publicholidays

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

import pandas as pd

wrangler_sample_df = pd.read_csv("https://aka.ms/wrangler/titanic.csv")
display(wrangler_sample_df)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark",
# META   "editable": true
# META }

# CELL ********************

# Code generated by Data Wrangler for pandas DataFrame

def clean_data(wrangler_sample_df):
    # Capitalize the first character in column: 'Name'
    wrangler_sample_df['Name'] = wrangler_sample_df['Name'].str.title()
    return wrangler_sample_df

wrangler_sample_df_clean = clean_data(wrangler_sample_df.copy())
display(wrangler_sample_df_clean)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
